# Generated by Django 5.1.6 on 2025-03-07 05:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid mobile number.')])),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Insurance', 'Insurance'), ('Rent', 'Rent'), ('Travel', 'Travel'), ('Education', 'Education'), ('Gifts', 'Gifts'), ('Fuel', 'Fuel'), ('Loans', 'Loans'), ('Investment', 'Investment'), ('Health', 'Health'), ('Other', 'Other')], db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('month', models.PositiveIntegerField(db_index=True, default=3)),
                ('year', models.PositiveIntegerField(db_index=True, default=2025)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Salary', 'Salary'), ('Bonus', 'Bonus'), ('Award', 'Award'), ('Refund', 'Refund'), ('Interest', 'Interest'), ('Dividends', 'Dividends'), ('Freelance', 'Freelance'), ('Business', 'Business'), ('Other', 'Other')], db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('month', models.PositiveIntegerField(db_index=True, default=3)),
                ('year', models.PositiveIntegerField(db_index=True, default=2025)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
